### ISSUE TITLE
URDF for qb SoftHand Research

### ISSUE THREAD

**Issue by MojaX2** [NMMI/SoftHand-Plugin#1]
We have two qb SoftHand Research ( left and right hand ) [1]. 
We would like to use our dual arm robot and two qb SoftHand Research in Gazebo.

I think this repository does not include qb SoftHand Research's URDF.
Do you plan to include qb SoftHand Research's URDF in this repository?

[1] https://qbrobotics.com/product/qb-softhand-research/

**Comment by gpollayil** [comment]
Hello @MojaX2,
Actually, you can use the `softhand_v1.urdf.xacro` to simulate the qb SoftHand Research. Even if the ourter palm stls are not exactly the same, the SoftHand version 1 is pretty close to the qb SoftHand Research.
